name: road-buddy
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pip
  - pip:
      - torch==2.6.0 --index-url=https://download.pytorch.org/whl/cu124
      - torchvision==0.21.0 --index-url=https://download.pytorch.org/whl/cu124
      - transformers
      - pyyaml
      - accelerate
      - flash-attn

