# Example configuration for training
batch_size: 32
epochs: 10
learning_rate: 0.001
model_name: "DAMO-NLP-SG/VideoLLaMA3-2B"
infer_data_path: "/kaggle/input/roadbuddy/public_test/public_test.json"
output_path: "/kaggle/working"
attn_implementation: "sdpa"  # Options: "flash_attention_2" or "sdpa"
